/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetvingraphique;

import ClassesMetier.Bouteille;
import ClassesMetier.Cepage;
import ClassesMetier.Couleur;
import ClassesMetier.Vin;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author fello
 */

public class frmVin extends javax.swing.JFrame {
     ArrayList<Bouteille> mesBouteilles = new ArrayList();
     Vector v;
     DefaultTableModel dtmInfos;

    /**
     * Creates new form frmVin
     */
    public frmVin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInfos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtMillesisme = new javax.swing.JTextField();
        txtPrix = new javax.swing.JTextField();
        txtCepage = new javax.swing.JTextField();
        txtCouleur = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtPourcentageRouge = new javax.swing.JTextField();
        txtPourcentageBlanc = new javax.swing.JTextField();
        txtPourcentageRosé = new javax.swing.JTextField();
        txtValeurCave = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("liste des bouteilles");

        tblInfos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "numéro", "Vin", "Quantité"
            }
        ));
        tblInfos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblInfosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblInfos);

        jLabel2.setText("millesisme");

        jLabel3.setText("prix");

        jLabel4.setText("cepage");

        jLabel5.setText("couleur");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("valeur de la cave");

        jLabel8.setText("pourcentage de Vin rouge");

        jLabel9.setText("pourcentage de Vin Blanc");

        jLabel10.setText("pourcentage de Vin rosé");

        txtValeurCave.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 383, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(101, 101, 101)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8)
                                            .addComponent(jLabel10))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtPourcentageBlanc, javax.swing.GroupLayout.DEFAULT_SIZE, 59, Short.MAX_VALUE)
                                            .addComponent(txtPourcentageRouge)
                                            .addComponent(txtPourcentageRosé)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3))
                                        .addGap(76, 76, 76)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(txtMillesisme)
                                            .addComponent(txtPrix)
                                            .addComponent(txtCepage)
                                            .addComponent(txtCouleur)))
                                    .addComponent(txtValeurCave)))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6)
                                .addGap(60, 60, 60)))))
                .addGap(72, 72, 72))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtMillesisme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtPrix, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtCepage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtCouleur, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(29, 29, 29)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(txtValeurCave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel8)
                                    .addComponent(txtPourcentageRouge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(36, 36, 36)
                                .addComponent(jLabel9))
                            .addComponent(txtPourcentageBlanc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(txtPourcentageRosé, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        
         
        dtmInfos = (DefaultTableModel) tblInfos.getModel();
        
        
        
        
         // Les couleurs du vin
        Couleur blanc = new Couleur("Blanc");
        Couleur rose = new Couleur("Rosé");
        Couleur rouge = new Couleur("Rouge");

        // Les cépages du vin
        Cepage beaujolais = new Cepage("Beaujolais");
        Cepage chardonnay = new Cepage("Chardonnay");
        Cepage gamay = new Cepage("Gamay");
        Cepage pinotNoir = new Cepage("Pinot noir");
        Cepage sauvignon = new Cepage("Sauvignon");

        // Les vins
        Vin vin1 = new Vin("Juliénas", 2005, beaujolais, rouge,13.78);
        Vin vin2 = new Vin("Saint Amour", 2012, beaujolais, blanc,18);
        Vin vin3 = new Vin("Brouilly", 2018, beaujolais, rouge,14.5);
        Vin vin4 = new Vin("Morgon", 2015, beaujolais, rose,21.34);
        Vin vin5 = new Vin("Bourgogne Côte de Beaune", 2002, chardonnay, blanc,39.5);
        Vin vin6 = new Vin("Aligoté", 2016, chardonnay, blanc,7.12);
        Vin vin7 = new Vin("Bourgogne Côte de Nuits", 2000, chardonnay, rose,11.67);
        Vin vin8 = new Vin("Chablis", 2011, chardonnay, blanc,15.17);
        Vin vin9 = new Vin("Champagne", 2014, chardonnay, blanc,24.71);
        Vin vin10 = new Vin("La Roche", 2005, gamay, rouge,12.45);
        Vin vin11 = new Vin("Le Carquelin", 2005, gamay, rouge,15.98);
        Vin vin12 = new Vin("Morgon Vieilles Vignes", 2005, gamay, rouge,19.54);
        Vin vin13 = new Vin("Coeurs de terroirs", 2005, gamay, rose,9.80);
        Vin vin14 = new Vin("Alox Corton", 2005, pinotNoir, rouge,17.65);
        Vin vin15 = new Vin("Edelzwicker ", 2017, pinotNoir, blanc,23.81);
        Vin vin16 = new Vin("Romanée Conti", 2009, pinotNoir, rouge,14.83);
        Vin vin17 = new Vin("Château d'Yguem", 2010, sauvignon, rose,11.56);
        Vin vin18 = new Vin("Château Guiraud", 2003, sauvignon, rouge,16.90);
        Vin vin19 = new Vin("Château Coutet", 2017, sauvignon, rouge,22.74);
        Vin vin20 = new Vin("Château Suduiraut", 2007, sauvignon, rouge, 8.63);

        // Les bouteilles
        Bouteille b1 = new Bouteille(1, 125, vin1);
        Bouteille b2 = new Bouteille(2, 56, vin2);
        Bouteille b3 = new Bouteille(3,23, vin3);
        Bouteille b4 = new Bouteille(4, 14, vin4);
        Bouteille b5 = new Bouteille(5, 87, vin5);
        Bouteille b6 = new Bouteille(6, 34, vin6);
        Bouteille b7 = new Bouteille(7, 78, vin7);
        Bouteille b8 = new Bouteille(8, 19, vin8);
        Bouteille b9 = new Bouteille(9, 41, vin9);
        Bouteille b10 = new Bouteille(10, 12, vin10);
        Bouteille b11 = new Bouteille(11, 25, vin11);
        Bouteille b12 = new Bouteille(12, 46, vin12);
        Bouteille b13 = new Bouteille(13, 62, vin13);
        Bouteille b14 = new Bouteille(14, 5, vin14);
        Bouteille b15 = new Bouteille(15, 44, vin15);
        Bouteille b16 = new Bouteille(16, 62, vin16);
        Bouteille b17 = new Bouteille(17, 21, vin17);
        Bouteille b18 = new Bouteille(18, 71, vin18);
        Bouteille b19 = new Bouteille(19, 37, vin19);
        Bouteille b20 = new Bouteille(20, 92, vin20);
        
       
        
        mesBouteilles.add(b1);mesBouteilles.add(b2);mesBouteilles.add(b3);
        mesBouteilles.add(b4);mesBouteilles.add(b5);mesBouteilles.add(b6);
        mesBouteilles.add(b7);mesBouteilles.add(b8);mesBouteilles.add(b9);
        mesBouteilles.add(b10);mesBouteilles.add(b11);mesBouteilles.add(b12);
        mesBouteilles.add(b13);mesBouteilles.add(b14);mesBouteilles.add(b15);
        mesBouteilles.add(b16);mesBouteilles.add(b17);mesBouteilles.add(b18);
        mesBouteilles.add(b19);mesBouteilles.add(b20);
        
        
        
        
        for (Bouteille btl : mesBouteilles)
        {
            v = new Vector();
            v.add(btl.getIdBouteille());
            v.add(btl.getLeVin().getNomVin());
            v.add(btl.getQuantiteBouteille());
            dtmInfos.addRow(v);
        }
        double montant = 0;
        int nbBouteillesRouge = 0;
        int nbBouteillesRose = 0;
        int nbBouteillesBlanc = 0;
        double i = 0;
                    for(Bouteille b : mesBouteilles)
                    {
                        montant = montant + b.getLeVin().getPrixDuVin() * b.getQuantiteBouteille();
                        
                        if("Rouge".equals(b.getLeVin().getLaCouleur().getNomCouleur()))
                        {
                            nbBouteillesRouge++;
                        }
                        if("Rosé".equals(b.getLeVin().getLaCouleur().getNomCouleur()))
                        {
                            nbBouteillesRose++;
                        }
                        if("Blanc".equals(b.getLeVin().getLaCouleur().getNomCouleur()))
                        {
                            nbBouteillesBlanc++;
                        }
                        i++;
                    }
                    txtValeurCave.setText(String.valueOf(montant));
                    txtPourcentageRouge.setText(String.valueOf((nbBouteillesRouge/i)*100)+"%");
                    txtPourcentageBlanc.setText(String.valueOf((nbBouteillesBlanc/i)*100)+"%");
                    txtPourcentageRosé.setText(String.valueOf((nbBouteillesRose/i)*100)+"%");
        
        
        
    }//GEN-LAST:event_formWindowOpened

    private void tblInfosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblInfosMouseClicked
        // TODO add your handling code here:
        
        //txtMillesisme.getDataVector().removeAllElements();
        int numVin;
        numVin = Integer.parseInt(tblInfos.getValueAt(tblInfos.getSelectedRow(), 0).toString());
        
        for(Bouteille b : mesBouteilles)
                    {
                        if(b.getIdBouteille()== numVin)
                        {
                            txtMillesisme.setText(String.valueOf(b.getLeVin().getMillesimeVin()));
                            txtPrix.setText(String.valueOf(b.getLeVin().getPrixDuVin()));
                            txtCepage.setText(String.valueOf(b.getLeVin().getLeCepage().getNomCepage()));
                            txtCouleur.setText(String.valueOf(b.getLeVin().getLaCouleur().getNomCouleur()));
                        }
                    }
        
    }//GEN-LAST:event_tblInfosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmVin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmVin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmVin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmVin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmVin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblInfos;
    private javax.swing.JTextField txtCepage;
    private javax.swing.JTextField txtCouleur;
    private javax.swing.JTextField txtMillesisme;
    private javax.swing.JTextField txtPourcentageBlanc;
    private javax.swing.JTextField txtPourcentageRosé;
    private javax.swing.JTextField txtPourcentageRouge;
    private javax.swing.JTextField txtPrix;
    private javax.swing.JTextField txtValeurCave;
    // End of variables declaration//GEN-END:variables
}
